# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialapp',
            name='key',
            field=models.CharField(blank=True, help_text='(required for certain Apps)', max_length=191, verbose_name='API key'),
        ),
    ]
